# Phase 1!

## Loading Files and Data Cleaning

```{r message=FALSE, warning=FALSE, results='hide'}
# required packages
install.packages("readxl")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("tidyverse")
install.packages("corrplot")
install.packages("gridExtra")
```

```{r}
# converting xlsx to csv, only needs to be run once
library(readxl)
library(dplyr)
data <- read_excel("data_academic_performance.xlsx")
write.csv(data, "data.csv") # cuz xlsx is not epic
df <- read.csv("data.csv")

df <- df %>% select(-X)
```

```{r}
head(df)
```

## Data Cleaning
```{r}
colnames(df)
```


```{r}
df_clean <- df %>% 
  mutate("AVG_S11" = (MAT_S11 + CR_S11 + CC_S11 + BIO_S11 + ENG_S11) / 5) %>%
  # select(G_SC, AVG_S11, GENDER, SCHOOL_NAT, SEL, SEL_IHE) 
  select(-c(Cod_SPro, COD_S11, UNIVERSITY, SCHOOL_NAME, ...10))
# dropping ID columns for SPro and S11, University and School Name to many unique values

continuous_cols <- c("MAT_S11", "CR_S11", "CC_S11", "BIO_S11", "ENG_S11", "G_SC", "AVG_S11",
                     "QR_PRO", "CR_PRO", "CC_PRO", "ENG_PRO", "WC_PRO", "FEP_PRO", "PERCENTILE",
                     "G_SC")

df_clean <- df_clean %>%
  mutate(across(!all_of(continuous_cols), as.factor))

df_numeric <- df_clean %>% select(continuous_cols)
df_categorical <- df_clean %>% select(-c(continuous_cols))
```

## Data Visualization

### Summary Statistics

```{r}
library(ggplot2)
library(tidyr)
library(corrplot)
```

```{r}
summary(df_clean)
```

### Visualizations for Numeric Data

```{r}
# pretty histogram for response

ggplot(df_clean, aes(x = G_SC)) + 
  geom_histogram() +
  geom_vline(aes(xintercept = mean(G_SC, na.rm = TRUE)), 
             color = "red", 
             linetype = "dashed", 
             size = 1) +
  labs(x = "Global Score (G_SC)",
       y = "Frequency",
       title = "Distribution of Global Score") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))
```



```{r}
lapply(names(df_numeric), function(col) {
  ggplot(df_numeric, aes(x = .data[[col]])) +
    geom_histogram(bins = 50) +
    labs(title = paste("Distribution of ", col))
})
```

```{r}
# correlation matrix
cor_matrix <- cor(df_numeric, use = "complete.obs")
corrplot(cor_matrix, method = "circle")
```

```{r}
# Relationship between G_SC and S11 tests
df_numerical_temp <- select(df_numeric, -c(QR_PRO, CR_PRO, CC_PRO, ENG_PRO, WC_PRO, FEP_PRO, PERCENTILE))
plot(df_numerical_temp, pch = 19, cex = 0.10)
```

```{r}
# Relationship between G_SC and PRO tests
df_numerical_temp <- select(df_numeric, -c(MAT_S11, CR_S11, CC_S11, BIO_S11, ENG_S11, AVG_S11, PERCENTILE))
plot(df_numerical_temp, pch = 19, cex = 0.10)
```

### Visualizing Categorical Data

```{r}
head(df_categorical)
```

```{r}
lapply(names(df_categorical), function(col) {
  ggplot(df_categorical, aes(x = .data[[col]])) +
    geom_bar() +
    labs(title = paste("Distribution of ", col)) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
})
```


### Visualizing Predictors against Response
```{r}
# selecting only chosen variables
features <- c("AVG_S11", "GENDER", "SCHOOL_NAT", "SEL", "SEL_IHE")
target <- "G_SC"
df_model <- df_clean %>% select(all_of(target), all_of(features))
```

```{r}
summary(df_model)
```

```{r}
library(gridExtra)

# function to generate the grid of plots
plot_matrix <- function(df) {
  vars <- names(df)
  n <- length(vars)
  
  plot_list <- lapply(1:n, function(i) {
    lapply(1:n, function(j) {
      
      # Diagonal: Variable name as text
      if (i == j) {
        label_text <- vars[i]
        p <- ggplot() + 
          geom_text(aes(x = 0.5, y = 0.5, label = label_text), size = 4) + 
          theme_void()
        
      } else {
        # base plot
        p <- ggplot(df, aes_string(x = vars[j], y = vars[i])) +
          theme_minimal(base_size = 10) +   # Use smaller font size to fit plots
          theme(
            # removing all labels and titles for now
            axis.text.x = element_blank(),
            axis.text.y = element_blank(),  
            axis.title.x = element_blank(), 
            axis.title.y = element_blank(), 
            plot.margin = margin(5, 5, 5, 5)
          )
        
        # Numeric vs. Numeric → Scatterplot
        if (is.numeric(df[[vars[j]]]) && is.numeric(df[[vars[i]]])) {
          p <- p + geom_point()
          
        # Categorical vs. Categorical → Count
        } else if (is.factor(df[[vars[j]]]) && is.factor(df[[vars[i]]])) {
          p <- p + geom_count(show.legend = FALSE)
          
        # Categorical vs. Numeric → Boxplot
        } else {
          p <- p + geom_boxplot()
        }
          
        # Show x-axis tick labels only for bottom row
        if (i == n && i != j) {
          p <- p + theme(axis.text.x = element_text(size = 8))
        }

        # Show y-axis tick labels only for leftmost column
        if (j == 1 && i != j) {
          p <- p + theme(axis.text.y = element_text(size = 8))
        }
      }
      
      return(p)
    })
  })
  
  plot_list <- unlist(plot_list, recursive = FALSE)
  grid.arrange(grobs = plot_list, ncol = n)
}

plot_matrix(df_model)

```

### Regression model

```{r}
head(df_model)
```

```{r}
lr <- lm(G_SC ~ ., data = df_model)
summary(lr)
```

### Residual Plots

```{r}
df_residual <- data.frame(fitted = fitted(lr), residuals = residuals(lr))
ggplot(df_residual, aes(x=fitted, y=residuals)) + geom_point(shape=1) + 
  geom_hline(yintercept = 0, color = "black") + labs(title = "Residuals vs Fitted Values") +
  xlab("Fitted Values") + ylab("Residuals")
```

```{r}
# residual plots against each variable
plots <- lapply(features, function(feature) {
  n <- length(features)
  
  if (is.numeric(df_model[[feature]])) {
    p <- ggplot(df_model, aes(x = .data[[feature]], y = lr$residuals)) +
      geom_point() + geom_hline(yintercept = 0, color = "darkblue") +
      labs(title = paste("Residuals vs", feature)) + 
      xlab(feature) + ylab("Residuals") +
      theme(plot.title = element_text(size = 10, margin = margin(b = 10)),
            plot.margin = margin(10, 10, 10, 10))
  } else {
    p <- ggplot(df_model, aes_string(x = feature, y = lr$residuals)) +
      geom_boxplot() + labs(title = paste("Residuals vs", feature)) + 
      xlab(feature) + ylab("Residuals") +
      theme(plot.title = element_text(size = 10, margin = margin(b = 10)),
            plot.margin = margin(10, 10, 10, 10))
  }
})

grid_plot <- do.call(grid.arrange, c(plots, ncol = n_cols))

```

```{r}
# qqplot
qqnorm(lr$residuals)
```

```{r}
# Standardized Residuals
std_residual <- rstandard(lr)
hist(std_residual, breaks = 50, xlab="Standardized Residual", main="Histogram of Standardized Residuals")
```

```{r}
# response vs fitted values
ggplot(df_model, aes(x = lr$fitted.values, y = df$G_SC)) +
  geom_point() + geom_hline(yintercept = 0, color = "darkblue") +
  labs(title = "Residuals vs Fitted Values") + geom_abline(intercept = 0, slope = 1, color="blue") +
  xlab("Fitted Values") + ylab("Global Score")
```
